<TR valign="top" height="34">
<TD background="../i/19.gif" valign="middle" class="copyr" align="right">&nbsp;</TD>
<TD background="../i/20.gif" valign="middle" class="copyr" align="left">&nbsp;&nbsp;Дизайн - &laquo;003&raquo;.&nbsp;&nbsp;Программирование - <a href="http://www.petroservice.ru/" target="_blank">&laquo;PetroService&raquo;</a>&nbsp;&nbsp;&copy; 2004</TD>
</TR>
</TABLE>
</BODY></HTML>