<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML><HEAD><TITLE>СПРАВОЧНАЯ СЛУЖБА 003</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=koi8-r">
<META http-equiv="Content-Language" content="ru">
<meta HTTP-EQUIV="imagetoolbar" content="no">
<meta name="author" content="Petro Service (c) 2004">
<meta name="keywords" content="дисконтная программа,персонал,справочная служба,003,о доставке,дисконтная программа,о бронировании лекарств,аптеки,все отделения дисконтной программы,о фирме,горячие линии,дисконтная карта,карта,дисконт,заказ препарата,лечебные туры,медицинские центры,партнерам,персонал,заказ препарата,вопрос,ваши вопросы,система скидок,участник,участники дисконтной программы,услуги,услуги компании">
<meta name="description" content="Сайт справочной службы 003">
<META NAME="rating" CONTENT="General">
<META NAME="revisit-after" CONTENT="15 days">
<META NAME="ROBOTS" CONTENT="ALL">
<META NAME="DC.Title" CONTENT="СПРАВОЧНАЯ СЛУЖБА 003">
<META NAME="DC.Creator" CONTENT="Petro Service (c) 2004">
<META NAME="DC.Subject" CONTENT="СПРАВОЧНАЯ СЛУЖБА 003">
<META NAME="DC.Description" CONTENT="СПРАВОЧНАЯ СЛУЖБА 003">
<link rel="stylesheet" type="text/css" href="../css/1.css">
<link rel="SHORTCUT ICON" href="../favicon.ico">
<SCRIPT language="JavaScript">
<!--
var FLAG = 0;
var linkTimeout = "";

function Blink() {
if (FLAG==0) {
   if (document.getElementById){
    document.getElementById("redlink").style.color = "#1122EE"; // "#315047";
   }else{
     redlink.style.color = "#1122EE"; // "#315047";
   }
   FLAG=1;
} else {
   if (document.getElementById){
    document.getElementById("redlink").style.color = "#EE1122";
   }else{
    redlink.style.color = "#EE1122";
   }
   FLAG=0;
}
linkTimeout = setTimeout("Blink()", 500);
}
//-->
</SCRIPT>
</HEAD>

<BODY OnLoad="Blink()" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<TABLE border="0" width="100%" cellpadding="0" cellspacing="0">
<TR valign="top">
<TD><a href="../index.php" TITLE="На главную"><IMG SRC="../i/top1_01.gif" width="166" height="103" border="0" ALT="На главную"></a></TD>
<TD background="../i/pixel.gif" width="100%" height="103" nowrap><IMG SRC="../i/top2_01.gif" width="575" height="103" border="0"><DIV STYLE="Z-INDEX:500; position:absolute; left:340px; top:85px;"><a href="../apteki.php" class="menulink">аптеки</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="../hotlines.php" class="menulink">горячие линии</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="../kurturs.php" class="menulink">лечебные туры</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="../medcenters.php" class="menulink">медицинские центры</a></DIV></TD>
</TR>

<TR valign="top">
<TD><IMG SRC="../i/top1_02.gif" width="166" height="34" border="0"><DIV STYLE="Z-INDEX:500; position:absolute; left:14px; top:103px"><a href="../index.php" class="menulink">информация о сайте</a></DIV></TD>
<TD bgcolor="#E9E9E9"><IMG SRC="../i/top2_02.gif" width="575" height="34" border="0"><DIV STYLE="Z-INDEX:500; position:absolute; left:165px; top:100px"><a href="../uslugi.php" class="menulink">услуги</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="../poisk.php" class="menulinkR" id="redlink" name="redlink">заказ лекарств</a></DIV></TD>
</TR>

<TR height="100%">
<TD><IMG SRC="../i/1.jpg" border="0" width="166" height="46" ALT=""></TD>
<TD bgcolor="#E9E9E9" valign="middle"><H1 align="right">Дисконтная программа&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</H1></TD>
</TR>

<TR valign="top" height="100%">
<TD>
<!-- left table begins -->
<table border="0" cellpadding="0" cellspacing="0" width="166" height="100%">
<tr valign="top">
<td><IMG SRC="../i/3.gif" border="0" width="166" height="22" alt=""></td>
</tr>
<tr valign="top">
<TD background="../i/17.gif" bgcolor="#E9E9E9"><DIV><img src="../i/5.gif" width="166" height="28" border="0" alt="" usemap="#id5_Map"></DIV>
<map name="id5_Map">
<area shape="poly" alt="" coords="12,28, 12,52, 138,52, 166,28" href="../index.php">
</map>
<!--begin of Rambler's Top100 code -->
<a href="http://top100.rambler.ru/top100/"><img src="http://counter.rambler.ru/top100.cnt?585574" alt="" width=1 height=1 border=0></a>
<!--end of Top100 code-->
&nbsp;&nbsp;&nbsp;<a href="../index.php" class="menulink">о сайте</a><BR>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="../about.php" class="menulink">о фирме</a><BR>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="../personal.php" class="menulink">персонал</a><BR>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="../dostavka.php" class="menulink">о доставке</a><BR>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="../bronirovanie.php" class="menulink">бронирование лекарств</a><BR>
<BR>
</TD>
</tr>
<tr valign="top">
<td><DIV><img src="../i/6.gif" width="166" height="22" border="0" alt="" usemap="#id6_Map"></DIV>
<map name="id6_Map">
<area shape="poly" alt="" coords="13,2, 13,22, 143,22, 164,3" href="poisk.php">
</map>
</td>
</tr>
<tr valign="top">
<td><DIV><img src="../i/7.gif" width="166" height="22" border="0" alt="" usemap="#id7_Map"></DIV>
<map name="id7_Map">
<area shape="poly" alt="" coords="13,3, 13,22, 141,22, 162,3" href="../uslugi.php">
</map>
</td>
</tr>
<tr valign="top">
<TD><DIV><img src="../i/9.gif" width="166" height="60" border="0" alt="" usemap="#id9_Map"></DIV>
<map name="id9_Map">
<area shape="poly" alt="" coords="13,34, 13,56, 137,56, 163,34" href="../apteki.php">
<area shape="poly" alt="" coords="13,7, 13,29, 137,29, 163,7" href="../partners.php">
</map>
</TD>
</tr>
<tr valign="top">
<TD><DIV><img src="../i/11.gif" width="166" height="22" border="0" alt="" usemap="#id11_Map"></DIV>
<map name="id11_Map">
<area shape="poly" alt="" coords="13,0, 13,22, 137,22, 163,0" href="../medcenters.php">
</map>
</TD>
</tr>
<tr valign="top">
<TD background="../i/17.gif" bgcolor="#E9E9E9"><DIV><IMG SRC="../i/13.gif" width="166" height="83" border="0" alt="" usemap="#id13_Map"></DIV>
<map name="id13_Map">
<area shape="poly" alt="" coords="13,32, 13,54, 136,54, 163,31" href="../kurturs.php">
<area shape="poly" alt="" coords="13,5, 13,27, 135,27, 163,5" href="../hotlines.php">
<area shape="poly" alt="" coords="13,57, 13,81, 136,81, 163,57" href="../discont.php">
</map>
</TD>
</tr>
<tr valign="top">
<TD background="../i/17.gif" bgcolor="#E9E9E9"><DIV><IMG SRC="../i/14.gif" width="166" height="27" border="0" alt="" usemap="#id14_Map"></DIV>
<map name="id14_Map">
<area shape="poly" alt="" coords="13,2, 13,27, 135,27, 164,2" href="../questions.php">
</map>
</tr>
<tr valign="top">
<TD background="../i/17.gif" bgcolor="#E9E9E9"><DIV><IMG SRC="../i/8.gif" width="166" height="22" border="0" alt="" usemap="#id8_Map"></DIV>
<map name="id8_Map">
<area shape="poly" alt="" coords="13,2, 13,22, 143,22, 164,2" href="../vakansii.php">
</map>
<BR>
<center>
<script>
document.write( '<a href="http://www.informer.ru/cgi-bin/redirect.cgi?id=177_1_1_45_40_1-0&url=http://www.rbc.ru&src_url=usd/eur_cb_forex_127815_88x90.gif" target="_blank"><img src="http://pics.rbc.ru/img/grinf/usd/eur_cb_forex_127815_88x90.gif?'+ Math.floor( 100000*Math.random() ) + '" WIDTH=88 HEIGHT="90" border=0></a>');
</script>
<br><br>
<script>
document.write( '<a href="http://www.informer.ru/cgi-bin/redirect.cgi?id=30_4_1_45_1_3-0&url=http://www.rbc.ru/meteo&src_url=weather/81x63_26063_green.gif" target="_blank"><img src="http://pics.rbc.ru/img/grinf/weather/81x63_26063_green.gif?'+ Math.floor( 100000*Math.random() ) + '" WIDTH=81 HEIGHT="63" border=0></a>');
</script>
<br><br>
<!--Rating@Mail.ru COUNTER--><script language="JavaScript" type="text/javascript"><!--
d=document;var a='';a+=';r='+escape(d.referrer)
js=10//--></script><script language="JavaScript1.1" type="text/javascript"><!--
a+=';j='+navigator.javaEnabled()
js=11//--></script><script language="JavaScript1.2" type="text/javascript"><!--
s=screen;a+=';s='+s.width+'*'+s.height
a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
js=12//--></script><script language="JavaScript1.3" type="text/javascript"><!--
js=13//--></script><script language="JavaScript" type="text/javascript"><!--
d.write('<a href="http://top.mail.ru/jump?from=714964"'+
' target=_top><img src="http://top.list.ru/counter'+
'?id=714964;t=53;js='+js+a+';rand='+Math.random()+
'" alt="Рейтинг@Mail.ru"'+' border=0 height=31 width=88/><\/a>')
if(11<js)d.write('<'+'!-- ')//--></script><noscript><a
target=_top href="http://top.mail.ru/jump?from=714964"><img
src="http://top.list.ru/counter?js=na;id=714964;t=53"
border=0 height=31 width=88
alt="Рейтинг@Mail.ru"/></a></noscript><script language="JavaScript" type="text/javascript"><!--
if(11<js)d.write('--'+'>')//--></script><!--/COUNTER-->
<br><br>
<!--begin of Top100 logo-->
<a href="http://top100.rambler.ru/top100/">
<img src="http://top100-images.rambler.ru/top100/w1.gif" alt="Rambler's 
Top100" width=88 height=31 border=0></a>
<!--end of Top100 logo -->
</center>

<BR>
</TD>
</tr>
<tr valign="top">
<td background="../i/17.gif" bgcolor="#E9E9E9" height="100%">&nbsp;</td>
</tr>
</table>
<!-- left table ends -->
</TD>
